# Generated by Django 6.0.1 on 2026-02-02 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_from_kg", models.DecimalField(decimal_places=2, max_digits=8)),
                ("weight_to_kg", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Base rate in RWF", max_digits=10
                    ),
                ),
                (
                    "per_kg_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate per additional kg in RWF",
                        max_digits=10,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["zone", "weight_from_kg"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone_number",
                    models.IntegerField(
                        choices=[
                            (1, "Zone 1 - Kigali"),
                            (2, "Zone 2 - Provinces"),
                            (3, "Zone 3 - EAC"),
                        ],
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "coverage_areas",
                    models.TextField(help_text="Comma-separated list of covered areas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["zone_number"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_base_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_base_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "old_per_kg_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "new_per_kg_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("changed_by", models.CharField(max_length=255)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="billing.tariff",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddField(
            model_name="tariff",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tariffs",
                to="billing.zone",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tariff",
            unique_together={("zone", "weight_from_kg", "weight_to_kg")},
        ),
    ]
