# Generated by Django 6.0.1 on 2026-02-02 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=20, unique=True)),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_phone", models.CharField(max_length=13)),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_TRANSIT", "In Transit"),
                            ("ARRIVED_HUB", "Arrived at Hub"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_shipments",
                        to="core.location",
                    ),
                ),
                (
                    "origin_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_shipments",
                        to="core.location",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.location",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="domestic.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["tracking_number"], name="domestic_sh_trackin_0fab4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["status"], name="domestic_sh_status_6308ab_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["sender"], name="domestic_sh_sender__5d0c9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipmentlog",
            index=models.Index(
                fields=["shipment", "timestamp"], name="domestic_sh_shipmen_6aebc1_idx"
            ),
        ),
    ]
