# Generated by Django 6.0.1 on 2026-02-02 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternationalShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=20, unique=True)),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_phone", models.CharField(max_length=13)),
                (
                    "destination",
                    models.CharField(
                        choices=[
                            ("KAMPALA", "Kampala, Uganda"),
                            ("NAIROBI", "Nairobi, Kenya"),
                            ("GOMA", "Goma, DRC"),
                            ("BUJUMBURA", "Bujumbura, Burundi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "sender_tin",
                    models.CharField(help_text="Rwanda TIN for sender", max_length=11),
                ),
                ("recipient_passport", models.CharField(blank=True, max_length=20)),
                ("recipient_tin", models.CharField(blank=True, max_length=11)),
                (
                    "hs_code",
                    models.CharField(
                        blank=True, help_text="Harmonized System Code", max_length=20
                    ),
                ),
                ("customs_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CLEARED_CUSTOMS_RW", "Cleared Rwanda Customs"),
                            ("IN_TRANSIT", "In Transit"),
                            ("ARRIVED_DESTINATION", "Arrived at Destination"),
                            ("CLEARED_CUSTOMS_DEST", "Cleared Destination Customs"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intl_origin_shipments",
                        to="core.location",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intl_shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomsDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("declaration_number", models.CharField(max_length=30, unique=True)),
                (
                    "declared_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("origin_country", models.CharField(default="RW", max_length=2)),
                ("destination_country", models.CharField(max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intl_shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customs_doc",
                        to="international.internationalshipment",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="internationalshipment",
            index=models.Index(
                fields=["tracking_number"], name="internation_trackin_c711b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internationalshipment",
            index=models.Index(
                fields=["destination", "status"], name="internation_destina_1a45a7_idx"
            ),
        ),
    ]
